timezone: America/Los_Angeles
encoding: utf-8

site_name: Link Extractor
site_description: Easily extract, parse, or open all links/domains from a site or text with optional filters.
site_url: https://link-extractor.cssnr.com
github_url: https://github.com/cssnr/link-extractor

chrome_url: https://chrome.google.com/webstore/detail/link-extractor/ifefifghpkllfibejafbakmflidjcjfp
firefox_url: https://addons.mozilla.org/addon/link-extractor
