timezone: America/Los_Angeles
encoding: utf-8

url: https://link-extractor.cssnr.com

author: Shane
site_name: Link Extractor

menu:
  - name: Home
    link: /
  - name: Documentation
    link: /docs/
  - name: Screen Shots
    link: /screenshots/

github_name: cssnr/link-extractor
github_url: https://github.com/cssnr/link-extractor

chrome_id: ifefifghpkllfibejafbakmflidjcjfp
chrome_url: https://chromewebstore.google.com/detail/link-extractor/ifefifghpkllfibejafbakmflidjcjfp

firefox_id: link-extractor
firefox_url: https://addons.mozilla.org/addon/link-extractor

discord_invite: https://discord.gg/wXy6m2X8wY
discord_webhook: https://relay.cssnr.com/discord/1258944618389569566
